### PR TITLE
correct and simplify the btbb_decode() procedure

### PR DESCRIPTION
**Pull request by elli89**

### CODE REVIEW

**Comment by dominicgs** [comment]
This changes clock to clkn for the purposes of unwhitening, but it doesn't then adjust the value for the additional bit in clkn.  Is that intentional?

**Comment by elli89** [comment]
I'm not sure if I understand your question correctly. Do you mean the LSB of clkn?

As I understood the code, clkn stores CLK1-27 or the 27 MSB bits of the the piconet clock CLK0-27 and thus ommits bit 0. This bit gets thrown away by a shift operation in btbb_packet_set_data().

The unwhitening procedure uses CLK1-6 or the 6 LSB bits of clkn or CLK1-27.

clock was never set but the comments in bluetooth_packet.h stated that it also stores the 27 MSB bits of CLK0-27.

So if I got it right, bit 0 of CLK0-27 is omitted in every case and never stored inside of libbtbb. Is that true? Was that the subject of your question?

Sorry if I got you wrong.

Hannes

**Comment by dominicgs** [comment]
Oh, I see.  clkn now represents what clock was meant to represent before, so there's no need to correct for a shift.

I think you're right about the lack of bit 0, although I'm sure there would be times that we need it, such as sniffing the inquiry scan.

**Comment by elli89** [comment]
Right, either the inquiry channel or the paging channel uses a hopping scheme that depends on bit 0 (I'm not sure which one. It has been a while since I've read the spec). We should change that in the future when we plan to support sniffing inquiry or paging. Since libbtbb omitted bit 0 in clkn and clock until now and all functions depend on that, I would leave this change out of this PR and preserve it for a future one.

**Pull request merged**
