### PR TITLE
support passive detection of the AFH channel map

### PR DESCRIPTION
**Pull request by elli89**
* add method clear_channel_seen() to tell the piconet that a channel is not used (any more)
* enhance the calculation of the hopping pattern to support AFH hopping patterns

These changes are part of an Ubertooth host tool for AFH channel map detection. This was the topic of my diploma thesis and I will commit it as soon as I have refactored it.

### CODE REVIEW

**Comment by dominicgs** [comment]
I like the improvements that you're bringing to libbtbb, but I have a concern about the memory/CPU performance of this change.

Assuming that we determine the UAP in approximately 6 packets, and that most hopping patterns are using at least 75% of the channels, then we'll generate around 56 hopping patterns for each piconet.

I'm wondering if it would make more sense to generate the non-AFH pattern for each piconet and perform the mapping to the AFH adjusted piconet at the time we retrieve it from the hash, rather than before storing it.

Do you think that is feasible?  Is there a reason to store the other hopping patterns?

**Comment by elli89** [comment]
You're right, the hopping pattern is really big (over 100 MiB each). So storing many of them in the memory does not make sense.

Maybe it's the best way to separate the calculation of the hopping pattern from setting a channel as used or unused. As you said, always calculate the non-AFH basic hopping pattern, then find out which channels are used and then the user has to manually start the recalculation of the AFH adaptive hopping pattern.

I fear that mapping the non-AFH hopping pattern to an AFH one each time the pattern is retrieved from its hash would cause a huge CPU load. So caching of at least one AFH hopping pattern is necessary.

I had decided to save more than one AFH hopping pattern because I want to make the Ubertooth follow an AFH piconet. If some bits in the channel map flip because of interference and flip back after some time, the host does not need to recalculate the pattern.

Let me think it over again. For now I will reduce the changes for this pull request so that it only contains the clear_channel_seen() method. That is enough to make my AFH detection approaches working for now. What do you think?

**Comment by dominicgs** [comment]
I think that's a great compromise for now.  I'd really like to get your AFH changes in to the library.

Isn't the AFH hopping pattern a simple remapping of the channels from the regular pattern?  I don't think that would be too big of a CPU load, would it?

**Comment by elli89** [comment]
Right, it's just a simple remapping task. But when trying to follow a piconet, it must be calculated for every received bluetooth packet times the remaining CLKN candidates. I will test how much CPU load these calculations will cause.

**Comment by elli89** [comment]
Thanks Dominic!

**Pull request merged**
